name: release-please
on:
  push:
    branches:
      - main
jobs:
  release-please:
    name: Release pls
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: "meilisearch-ui"
          pull-request-title-pattern: "chore(release): v${version}"
          token: ${{ secrets.GH_TOKEN }}

      - name: Echo status of release-please
        env:
          RELEASES_CREATED: ${{ steps.release.outputs.releases_created }}
          RELEASE_CREATED: ${{ steps.release.outputs.release_created }}
        run: |
          echo "releases_created: $RELEASES_CREATED"
          echo "release_created: $RELEASE_CREATED"